# Managed by Ansible (zsh_config role). Do not edit manually.
# Ported from oh-my-zsh git plugin.

alias g="git"
alias ga="git add"
alias gaa="git add --all"
alias gb="git branch"
alias gba="git branch --all"
alias gc="git commit --verbose"
alias gcm="git commit --message"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gcp="git cherry-pick"
alias gd="git diff"
alias gds="git diff --staged"
alias gf="git fetch"
alias gfa="git fetch --all --prune"
alias gl="git pull"
alias glg="git log --stat"
alias glog="git log --oneline --decorate --graph"
alias gm="git merge"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias grb="git rebase"
alias grba="git rebase --abort"
alias grbc="git rebase --continue"
alias grbi="git rebase --interactive"
alias grs="git restore"
alias grss="git restore --staged"
alias gst="git status"
alias gsw="git switch"
alias gswc="git switch --create"
