---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart ttyd
  ansible.builtin.systemd:
    name: ttyd
    state: restarted
  become: true
