---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart coredns
  ansible.builtin.systemd:
    name: coredns
    state: restarted
  become: true

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  become: true
