---
- name: Restart code-server
  ansible.builtin.systemd:
    name: code-server@{{ ansible_user }}
    state: restarted
  become: true

- name: Restart coredns
  ansible.builtin.systemd:
    name: coredns
    state: restarted
  become: true
