#!/usr/bin/env bash
# gen-inventory.sh — Generate ansible/hosts.yml from Tailscale status.
#
# Uses Tailscale as the source of truth for server connectivity:
#   - Filters peers that carry tag:dev-env.
#   - Maps tag:dev-env → Ansible group "dev-env".
#   - Uses the actual Tailscale IP as ansible_host — no MagicDNS dependency,
#     no hostname-collision problems.
#
# Per-server usernames are read from `terraform output -json server_usernames`.
# Falls back to $ANSIBLE_USER or "ikaros" if Terraform state is unavailable.
#
# Run this after every `terraform apply` or whenever the tailnet topology changes.
# The generated file is gitignored (environment-specific).
#
# Usage:
#   bash scripts/gen-inventory.sh [--tf-dir|-d <path>]
#
#   --tf-dir / -d   Path to the Terraform root module to read server_usernames
#                   from.  Defaults to ../terraform/hetzner relative to this
#                   script.  Pass ../terraform/digitalocean (or an absolute path)
#                   when managing DigitalOcean droplets.
#
# Requirements: tailscale (in PATH), python3 (in PATH)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INVENTORY_FILE="$SCRIPT_DIR/../ansible/hosts.yml"
# TF_DIR env var can override the default; --tf-dir/-d flag takes highest precedence.
TF_DIR="${TF_DIR:-$SCRIPT_DIR/../terraform/hetzner}"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    -d|--tf-dir)
      TF_DIR="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      echo "Usage: $0 [--tf-dir|-d <terraform-dir>]" >&2
      exit 1
      ;;
  esac
done

# Resolve to absolute path (handles both relative and absolute input)
TF_DIR="$(cd "$TF_DIR" && pwd)"

echo "Reading Tailscale status..."

STATUS_JSON=$(tailscale status --json)

# Attempt to read per-server usernames from Terraform output.
if command -v terraform &>/dev/null && [ -f "$TF_DIR/terraform.tfstate" ]; then
  echo "Reading usernames from Terraform state ($TF_DIR)..."
  USERNAME_JSON=$(terraform -chdir="$TF_DIR" output -json server_usernames 2>/dev/null || echo '{}')
else
  USERNAME_JSON='{}'
fi
DEFAULT_USER="${ANSIBLE_USER:-ikaros}"

python3 - "$STATUS_JSON" "$USERNAME_JSON" "$DEFAULT_USER" > "$INVENTORY_FILE" <<'PYEOF'
import json, sys
from collections import defaultdict

status = json.loads(sys.argv[1])
username_map = json.loads(sys.argv[2])
default_user = sys.argv[3]

# Include Self so the inventory is correct when the script runs on a managed server.
self_node = status.get("Self")
self_ip = self_node["TailscaleIPs"][0] if self_node else None

peers = list(status.get("Peer", {}).values())
if self_node:
    peers.append(self_node)

# Maps Tailscale tag → Ansible inventory group name.
ROLE_TAGS = {
    "tag:dev-env": "dev-env",
}

groups = defaultdict(list)

for peer in peers:
    tags = peer.get("Tags") or []
    group = next((ROLE_TAGS[t] for t in tags if t in ROLE_TAGS), None)
    if group is None:
        continue

    hostname = peer["HostName"]
    tailscale_ip = peer["TailscaleIPs"][0]
    is_self = tailscale_ip == self_ip
    user = username_map.get(hostname, default_user)
    groups[group].append((hostname, tailscale_ip, is_self, user))

lines = [
    "# Auto-generated by scripts/gen-inventory.sh — do not edit by hand.",
    "# Re-run after `terraform apply` or tailnet topology changes.",
    "---",
    "all:",
    "  children:",
]

for group_name, members in sorted(groups.items()):
    lines.append(f"    {group_name}:")
    lines.append(f"      hosts:")
    for hostname, ip, is_self, user in sorted(members):
        lines.append(f"        {hostname}:")
        lines.append(f"          ansible_host: {ip}")
        lines.append(f"          ansible_user: {user}")
        if is_self:
            lines.append(f"          ansible_connection: local")

print("\n".join(lines))
PYEOF

echo "Inventory written to $INVENTORY_FILE"
