#!/usr/bin/env bash
# gen-inventory.sh — Generate ansible/hosts.ini from Terraform output.
#
# Uses the Terraform server_usernames output as the source of truth:
#   - Server names (Terraform resource keys) become inventory hostnames.
#   - ansible_host is set to the server name, resolved via Tailscale MagicDNS.
#   - All servers map to the Ansible group "dev-env".
#   - ansible_user is read from the server_usernames output.
#
# Run this after every `terraform apply`.
# The generated file is gitignored (environment-specific).
#
# Usage:
#   bash scripts/gen-inventory.sh [--tf-dir|-d <path>]
#
#   --tf-dir / -d   Path to the Terraform root module to read server_usernames
#                   from.  Defaults to ../terraform/hetzner relative to this
#                   script.  Pass ../terraform/digitalocean (or an absolute path)
#                   when managing DigitalOcean droplets.
#
# Requirements: terraform (in PATH), python3 (in PATH)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INVENTORY_FILE="$SCRIPT_DIR/../ansible/hosts.ini"
# TF_DIR env var can override the default; --tf-dir/-d flag takes highest precedence.
TF_DIR="${TF_DIR:-$SCRIPT_DIR/../terraform/hetzner}"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    -d|--tf-dir)
      TF_DIR="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      echo "Usage: $0 [--tf-dir|-d <terraform-dir>]" >&2
      exit 1
      ;;
  esac
done

# Resolve to absolute path (handles both relative and absolute input)
TF_DIR="$(cd "$TF_DIR" && pwd)"

if ! command -v terraform &>/dev/null; then
  echo "Error: terraform not found in PATH" >&2
  exit 1
fi

if [ ! -f "$TF_DIR/terraform.tfstate" ]; then
  echo "Error: no terraform.tfstate found in $TF_DIR" >&2
  echo "Run 'terraform apply' first." >&2
  exit 1
fi

echo "Reading server list from Terraform state ($TF_DIR)..."
USERNAME_JSON=$(terraform -chdir="$TF_DIR" output -json server_usernames 2>/dev/null || echo '{}')

DEFAULT_USER="${ANSIBLE_USER:-ikaros}"

python3 - "$USERNAME_JSON" "$DEFAULT_USER" > "$INVENTORY_FILE" <<'PYEOF'
import json, socket, sys

username_map = json.loads(sys.argv[1])
default_user = sys.argv[2]
self_hostname = socket.gethostname().split('.')[0]

lines = [
    "# Auto-generated by scripts/gen-inventory.sh — do not edit by hand.",
    "# Re-run after `terraform apply`.",
    "",
    "[dev_env]",
]

for server_name, user in sorted(username_map.items()):
    entry = f"{server_name}  ansible_host={server_name}  ansible_user={user or default_user}"
    if server_name == self_hostname:
        entry += "  ansible_connection=local"
    lines.append(entry)

print("\n".join(lines))
PYEOF

echo "Inventory written to $INVENTORY_FILE"
