namespace: ikaros_labs
name: dev_env
version: 1.0.0
readme: README.md
description: Shared Ansible roles for ikaros-labs infrastructure
authors:
  - ikaros
repository: https://github.com/ikaros-labs/dev-env
