---
galaxy_info:
  role_name: code_server
  author: ikaros-iac
  description: Install code-server from the official packagecloud apt repository
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble  # 24.04 LTS

dependencies: []
